### ISSUE TITLE
undefined function browsealllink_to_collection in index.php of Scribe theme

### ISSUE THREAD

**Issue by rileyjrs** [LibraryofVA/MakingHistory-transcribe-2.0#1]
Hi -

We installed the following:
Omeka 	2.4.1
PHP 	7.0.14 (cgi-fcgi)
OS 	Linux 3.2.61-grsec-modsign x86_64
MySQL Server 	5.6.28
MySQL Client 	mysqlnd 5.0.12-dev - 20150407 - $Id: 241ae00989d1995ffcbbf63d579943635faf9972 $
Dropbox 	0.7.2
DublinCoreExtended 	2.0.1
Export 	2.0
Scripto 	2.2
SimplePages 	3.0.7
Scribe 	2.0 (current)

When we go to this url:
http://www.nsmlv.org/omeka_test/omeka/index.php
These errors appear:
Fatal error: Uncaught Error: Call to undefined function browsealllink_to_collection() in /home/lan_t3rn/nsmlv.org/omeka_test/omeka/themes/Scribe/index.php:24 Stack trace: #0 /home/lan_t3rn/nsmlv.org/omeka_test/omeka/application/libraries/Omeka/View.php(117): include() #1 /home/lan_t3rn/nsmlv.org/omeka_test/omeka/application/libraries/Zend/View/Abstract.php(888): Omeka_View->_run('/home/lan_t3rn/...') #2 /home/lan_t3rn/nsmlv.org/omeka_test/omeka/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(912): Zend_View_Abstract->render() #3 /home/lan_t3rn/nsmlv.org/omeka_test/omeka/application/controllers/IndexController.php(16): Zend_Controller_Action_Helper_ViewRenderer->renderScript('index.php') #4 /home/lan_t3rn/nsmlv.org/omeka_test/omeka/application/libraries/Zend/Controller/Action.php(516): IndexController->indexAction() #5 /home/lan_t3rn/nsmlv.org/omeka_test/omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('indexAction') #6 /home/lan_t3rn/nsmlv.org/ in /home/lan_t3rn/nsmlv.org/omeka_test/omeka/themes/Scribe/index.php on line 24

Are we navigating incorrectly or is there a problem with our configuration?  If it's a configuration problem, how do we fix it?

Thanks

**Comment by jasonroma** [comment]
Hi rileyjrs,

Weird timing. I did a fresh install earlier today for a new project and
received the same error. It is due to an ill placed function I created back
in 2014. Add the below function to application/libraries/global.php in your
Omeka installation to get things working.

I am working on figuring out where I can move the function to inside the
Scripto plugin or Scribe theme.

/** browse all style of link to collection, added by Jason Roma 4/11/2014
**/
function browsealllink_to_collection($text=null, $props=array(),
$action='show', $collectionObj = null)
{
    if (!$collectionObj) {
        $collectionObj = get_current_record('collection');
    }

    $collectionName = metadata($collectionObj, array('Dublin Core',
'Title'));
    $text = (!empty($text) ? $text : (!empty($collectionName) ?
$collectionName : __('[Untitled]')));
    return " (" . link_to($collectionObj, $action, "browse all", $props) .
")";
}

**Comment by jasonroma** [comment]
Please make the adjustment found at
https://github.com/LibraryofVA/Scribe-2.0/commit/7fab7252f57068864ea81c7bc18f29d6fbc9ec5a

Thanks,
Jason Roma

**Comment by rileyjrs** [comment]
Hi Jason -

Thank you for your prompt response!  We made the changes described at https://github.com/LibraryofVA/Scribe-2.0/commit/7fab7252f57068864ea81c7bc18f29d6fbc9ec5a.  We also made sure the permissions on the edited file are -rw-rw-r--  to match the original file.  Now we get an http 500 error.  Please see below for the contents of the edited index.php file.  Do you know where we went wrong?

<?php
echo head(array('bodyid' => 'home'));

ini_set('display_errors',1);
error_reporting(E_ALL);

?>

<div id="primary">
    <?php if (get_theme_option('Homepage Text')): ?>
    <p><?php echo get_theme_option('Homepage Text'); ?></p>
    <?php endif; ?>

<?php
    $collectionTitle = '';
    $collectionIDs = collection_order_array();
    $num_of_collections = count($collectionIDs);
    $div_counter = 1;

    foreach ($collectionIDs as $collectionID) {

        $collection = get_record_by_id('collection', $collectionID);
        $collectionName = metadata($collection, array('Dublin Core', 'Title'));
        $collection_link = link_to_collection('browse all', array(), 'show', $collection);
        $collection_items = get_records('Item',
            array(
                'collection' => $collection['id'],
                'sort_field' => 'Dublin Core,Audience',
                'sort_dir' => 'a',
            ),
            999);

        $num_of_collection_items = count($collection_items);

        set_loop_records('items', $collection_items);
        $collection_item_list = array();
        foreach (loop('items') as $item) {
            set_current_record('item', $item);
            array_push($collection_item_list,
                array(
                    'thumb' => item_image('square_thumbnail', array('alt' => metadata($item, array('Dublin Core', 'Title')))),
                    'link' => record_url($item),
                    'name' => metadata($item, array('Dublin Core', 'Title')),
             ));
        }

        echo '<h1 style="display: inline;">' .$collectionName. '</h1> (' . $collection_link ')';
        echo '<hr style="visibility: hidden; margin-top: 2px; margin-bottom: 4px;" />';
        echo '<ul id="collection'.$div_counter.'" class="slider">';

        for ($i=0; $i < $num_of_collection_items; $i++) {
            echo '<li>';
            echo '<a href="'.$collection_item_list[$i]['link'].'" rel="tooltip" title="'.$collection_item_list[$i]['name'].'">'.$collection_item_list[$i]['thumb'].'</a>';
            echo '</li>';
        }

        echo '</ul>';
        echo '<hr style="visibility: hidden; margin-top: 3px; margin-bottom: 3px;" />';
        $div_counter++;

    }

    echo "<script> " . PHP_EOL;
    echo "!function( $ ){ " . PHP_EOL;
    echo "$(function () { " . PHP_EOL;

    for ($k=1; $k <= $num_of_collections; $k++) {
        echo "$('#collection".$k."').bxSlider({ " . PHP_EOL;
        echo "displaySlideQty: 7, " . PHP_EOL;
        echo "moveSlideQty: 7 " . PHP_EOL;
        echo " }); " . PHP_EOL;
    }

    echo "$('a[rel=tooltip]').tooltip(); " . PHP_EOL;
    echo "}); " . PHP_EOL;
    echo "}( window.jQuery ) " . PHP_EOL;
    echo "</script> " . PHP_EOL;

    fire_plugin_hook('public_home', array('view' => $this));
    echo foot();
 ?>

**Comment by jasonroma** [comment]
Hmm. I don't think your code came through completely. Did you use the Insert Code toolbar button (same tool bar as Bold and Italics) when posting your comment to GitHub? If not can you re-post the code using that button, thanks.

**Comment by rileyjrs** [comment]
`<?php
echo head(array('bodyid' => 'home'));

ini_set('display_errors',1);
error_reporting(E_ALL);

?>

<div id="primary">
    <?php if (get_theme_option('Homepage Text')): ?>
    <p><?php echo get_theme_option('Homepage Text'); ?></p>
    <?php endif; ?>

<?php
    $collectionTitle = '';
    $collectionIDs = collection_order_array();
    $num_of_collections = count($collectionIDs);
    $div_counter = 1;

    foreach ($collectionIDs as $collectionID) {

        $collection = get_record_by_id('collection', $collectionID);
        $collectionName = metadata($collection, array('Dublin Core', 'Title'));
        $collection_link = link_to_collection('browse all', array(), 'show', $collection);
        $collection_items = get_records('Item',
            array(
                'collection' => $collection['id'],
                'sort_field' => 'Dublin Core,Audience',
                'sort_dir' => 'a',
            ),
            999);

        $num_of_collection_items = count($collection_items);

        set_loop_records('items', $collection_items);
        $collection_item_list = array();
        foreach (loop('items') as $item) {
            set_current_record('item', $item);
            array_push($collection_item_list,
                array(
                    'thumb' => item_image('square_thumbnail', array('alt' => metadata($item, array('Dublin Core', 'Title')))),
                    'link' => record_url($item),
                    'name' => metadata($item, array('Dublin Core', 'Title')),
             ));
        }

        echo '<h1 style="display: inline;">' .$collectionName. '</h1> (' . $collection_link ')';
        echo '<hr style="visibility: hidden; margin-top: 2px; margin-bottom: 4px;" />';
        echo '<ul id="collection'.$div_counter.'" class="slider">';

        for ($i=0; $i < $num_of_collection_items; $i++) {
            echo '<li>';
            echo '<a href="'.$collection_item_list[$i]['link'].'" rel="tooltip" title="'.$collection_item_list[$i]['name'].'">'.$collection_item_list[$i]['thumb'].'</a>';
            echo '</li>';
        }

        echo '</ul>';
        echo '<hr style="visibility: hidden; margin-top: 3px; margin-bottom: 3px;" />';
        $div_counter++;

    }

    echo "<script> " . PHP_EOL;
    echo "!function( $ ){ " . PHP_EOL;
    echo "$(function () { " . PHP_EOL;

    for ($k=1; $k <= $num_of_collections; $k++) {
        echo "$('#collection".$k."').bxSlider({ " . PHP_EOL;
        echo "displaySlideQty: 7, " . PHP_EOL;
        echo "moveSlideQty: 7 " . PHP_EOL;
        echo " }); " . PHP_EOL;
    }

    echo "$('a[rel=tooltip]').tooltip(); " . PHP_EOL;
    echo "}); " . PHP_EOL;
    echo "}( window.jQuery ) " . PHP_EOL;
    echo "</script> " . PHP_EOL;

    fire_plugin_hook('public_home', array('view' => $this));
    echo foot();
 ?>
`

**Comment by rileyjrs** [comment]
Hi -
We tried reposting the code.  Hopefully, that got it all.

**Comment by jasonroma** [comment]
Thanks,

I am not sure how much I should be reading into the code your pasting. Is
that the whole file? If so there is no <?php before the line that begins
with $collection['id']. And I don't recognize that piece of code and
couldn't find
$collection['id'] anywhere on our site or in GitHub. There is other missing
syntax too.  I noticed that it looks like you have your install in a
sub-directory of root (http://www.nsmlv.org/omeka_test/omeka/) which has
given me problems in the past. Transcribe was originally meant to live in a
sub-directory but after failed attempts of doing so it lives in a directory
at the root level.

Can you update your live code at http://www.nsmlv.org/omeka_test/omeka/
removing the browsealllink_to_collection() function call replacing it with
link_to_collection(). You wouldn't have to change any other code yet as
that should fix the issue the link text would just be duplicate.

Also notice what looks like a dot in the code but it could still be a code
rendering problem on GitHub.

**Comment by rileyjrs** [comment]
Hi Jason -

Since there have been problems with the uploaded code, please check the index.php file at this location:

https://www.dropbox.com/s/nxwrm79mzlpp300/index.php?dl=0

If there are no errors in the file, I will reinstall everything in a root directory.

Thank you for your help!

**Comment by jasonroma** [comment]
Thank you,

The dropbox file was extremely helpful. The problem was in my code I updated on GitHub, I missed a period between $collection_link and the closing bracket string. I've pasted code below and fixed GitHub. Thank you for sticking with the problem. There is nothing better then someone else testing your code to make it better. Please let me know if everything works now as I hope it should. 

Line #47
`echo '<h1 style="display: inline;">' .$collectionName. '</h1> (' . $collection_link ')';`

Should be 
`echo '<h1 style="display: inline;">' .$collectionName. '</h1> (' . $collection_link . ')';`

**Comment by rileyjrs** [comment]
Hi Jason -

Thank you very much!  Adding the period fixed the problem!  We truly appreciate your help.
