### ISSUE TITLE
undefined function mysql_connect scribe theme in footer.php line 25

### ISSUE THREAD

**Issue by rileyjrs** [LibraryofVA/MakingHistory-transcribe-2.0#2]
Hello -

When we open our omeka site, we get the error listed below.  We tried hard-coding the database connection information in the footer.php file ($user="xxx"; $pwd="xxx";, etc) but the error still occurs.  Our db.ini file is correctly configured.  We checked the Scribe settings tab in omeka, and didn't see a way to configure this.  Did we miss it?

Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /home/lan_t3rn/nsmlv.org/omeka_test/omeka/themes/Scribe/common/footer.php:25 Stack trace: #0 /home/lan_t3rn/nsmlv.org/omeka_test/omeka/themes/Scribe/common/footer.php(46): countFinished() #1 /home/lan_t3rn/nsmlv.org/omeka_test/omeka/application/libraries/Omeka/View.php(117): include('/home/lan_t3rn/...') #2 /home/lan_t3rn/nsmlv.org/omeka_test/omeka/application/libraries/Zend/View/Abstract.php(888): Omeka_View->_run('/home/lan_t3rn/...') #3 /home/lan_t3rn/nsmlv.org/omeka_test/omeka/application/libraries/Zend/View/Helper/Partial.php(109): Zend_View_Abstract->render() #4 /home/lan_t3rn/nsmlv.org/omeka_test/omeka/application/libraries/Zend/View/Abstract.php(349): Zend_View_Helper_Partial->partial('common/footer.p...', Array) #5 /home/lan_t3rn/nsmlv.org/omeka_test/omeka/application/libraries/globals.php(1656): Zend_View_Abstract->__call('partial', Array) #6 /home/lan_t3rn/nsmlv.org/omeka_test/omeka/application/libraries/globals.php(1684): common('footer in /home/lan_t3rn/nsmlv.org/omeka_test/omeka/themes/Scribe/common/footer.php on line 25

**Comment by jasonroma** [comment]
There are two instances of hard-coded database creds in the footer. One gives a transcription count from Omeka, the other is a leaderboard from MediaWiki. If you can't get the connections to work you may have to remove one or both as they have nothing to do with db.ini or Scribe but are stand-alone.  From your error trace it appears you don't have the PHP function mysql_connect(). That built-in function was removed in PHP 7.x but replaced with other functions.
