### ISSUE TITLE
transcription does not appear with the image on the Scripto tab

### ISSUE THREAD

**Issue by rileyjrs** [LibraryofVA/MakingHistory-transcribe-2.0#3]
Hi -

This is our system information:
System

Omeka 2.4.1 
PHP 7.0.14 (cgi-fcgi) 
OS Linux 3.2.61-grsec-modsign x86_64 
MySQL Server 5.6.34 
MySQL Client mysqlnd 5.0.12-dev - 20150407 - 
PHP Extensions

Regular bcmath, bz2, calendar, cgi-fcgi, Core, ctype, curl, date, dom, exif, filter, ftp, gd, gettext, hash, iconv, imagick, imap, json, libxml, mbstring, mcrypt, mysqli, mysqlnd, openssl, pcntl, pcre, PDO, pdo_mysql, pdo_sqlite, posix, pspell, Reflection, session, SimpleXML, soap, sockets, SPL, sqlite3, standard, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, Zend OPcache, zip, zlib 
Zend Zend OPcache

Plugins

Dropbox 0.7.2 
DublinCoreExtended 2.0.1 
Export 2.0 
Scripto 2.2 
SimplePages 3.0.7

Themes

Scribe 2.0 (current) <= from UVA

We think the way to approve transcriptions is as follows:
1 ) the admin user logs into omeka
2) go to the item page
3) click on the Scripto tab
4) manually type "complete" in the status box
5) click "save changes"

However, when a user transcribes a file, the transcription does not appear with the image on the Scripto tab. What are we doing wrong?  Please see the screenshots below.

![omeka-public](https://cloud.githubusercontent.com/assets/26339345/25032178/fa31de1a-2086-11e7-895e-81400a5a4428.jpg)
![omeka-scripto-edit](https://cloud.githubusercontent.com/assets/26339345/25032180/fa893a84-2086-11e7-87e7-e891e09405de.jpg)
![omeka-scripto-file](https://cloud.githubusercontent.com/assets/26339345/25032179/fa37b420-2086-11e7-827a-951da1073bf2.jpg)

**Comment by jasonroma** [comment]
Transcriptions should be approved via the user or public facing interface with a Scripto (aka MediaWiki) account. Screenshots below show the difference between an anonymous user and one logged in with approval rights. The Scripto plugin copies transcription information from MediaWiki into Omeka during approval. 
![image](https://cloud.githubusercontent.com/assets/8026638/25114869/04cd7540-23d0-11e7-8726-6207f52b489f.png)
![image](https://cloud.githubusercontent.com/assets/8026638/25114991/d40100ac-23d0-11e7-949b-314c1640c60e.png)

**Comment by rileyjrs** [comment]
Thank you for your help!
