### ISSUE TITLE
Number of pages transcribed not displaying

### ISSUE THREAD

**Issue by rileyjrs** [LibraryofVA/MakingHistory-transcribe-2.0#4]
Hi-

It appears that line 41 of the footer.php file downloaded from https://github.com/LibraryofVA/plugin-Scripto-2.0 has a hard-coded value of 785 that is displaying as the number of pages transcribed although the comments in the code suggest it should be tracking deleted items.  For our system (www.nsmlv.org/omeka) this database query at line 33 in the downloaded footer.php file does not return a count of completed transcriptions:

SELECT COUNT( * ) FROM omeka_element_texts WHERE (text = 'Completed')

We edited the footer.php file for some customizations, but we don't think we broke the code and that there may be some problems.  Our edited footer.php file is shown below.  Is there a problem with the original code or did we break something?

        </article>

        <div id="footer">
           <hr />
           <div class="footer">
              <div class="row2">
              <div class="span3-linda bar-linda about">
                <h3>About</h3>
                <ul>
                  <li><a href="https://www.nsmlv.org/omeka/about">About the project</a></li>
                  <li><a href="https://www.nsmlv.org/omeka/faq">FAQ</a></li>
                  <li><a href="https://www.nsmlv.org/omeka/tips">Transcription tips</a></li>
                  <li><a href="https://www.nsmlv.org/omeka/contact">Contact us</a></li>
                </ul>
                <h3>Contribute</h3>
                <ul>
				  <li><?php
				  //function to count completed items and provide that number on the page
                  function countFinished() {
					$usr = "xxx";
					$pwd = "xxx";
					$db = "xxx";
					$host = "xxx";

					$con = mysqli_connect($host, $usr, $pwd);

					if (!$con) {
						die('Could not connect.');
					}

					mysqli_select_db($con, $db);

					$result = mysqli_query($con, "SELECT COUNT( * ) FROM omeka_element_texts WHERE (text = 'Completed')") or die(mysqli_error());

					while ($rows = mysqli_fetch_array($result)) {
						$count = $rows[0];
						$total = (int)$count;
					}
					mysqli_close($con);
					//account for items deleted from Omeka
					$total_int = intval($total) +467;
					//format and string out
					$total_str = number_format(strval($total_int));
					return $total_str;
				  }
				  echo countFinished();
				  ?> pages transcribed</li>
                </ul>
              </div>
              <div class="span3-linda bar-linda connect">
                <h3>Connect With Us</h3>
                <div id="connected">
			        <a title="Join us on Facebook" href="https://www.facebook.com/nsmlv.org"><img src="/images/color-facebook-48.png"></a> <a title="The Friends of Nevada State Museum Home" href="https://www.nsmlv.org"><img src="/images/color-link-48.png"></a>
		        </div>
              </div>
              <div class="span3-linda bar-linda leaderboard">
              	<?php
					$usr = "xxx";
					$pwd = "xxx";
					$db = "xxx";
					$host = "xxx";

					$con = mysqli_connect($host, $usr, $pwd);

					if (!$con) {
						die('Could not connect.');
					}
					mysqli_select_db($con, $db);
				?>

              </div>
            </div>
        </div>
    </div>
</body>
</html>

**Comment by jasonroma** [comment]
Just in case, I think you meant https://github.com/LibraryofVA/Scribe-2.0/ and not plugin-Scripto-2.0. 
First let me address "deleted items." After a collection has been completely transcribed, we export it, add the full text to our catalog or digital asset management system, and delete it from Transcribe (Omeka and MediaWiki). Line 41 allows us to add those "deleted" items back in to the total completed count.

**Comment by jasonroma** [comment]
Line 33: omeka_element_texts is the table you are querying. Double check your Omeka db.ini file specifically your prefix setting in that file. If your prefix is not omeka_ then you need to update your line 33 to match.
