### ISSUE TITLE
problems upgrading to MediaWiki 1.29.0

### ISSUE THREAD

**Issue by rileyjrs** [LibraryofVA/MakingHistory-transcribe-2.0#5]
Hi -  

We tried to upgrade from MediaWiki 1.27.1 to 1.29.0 while using the nice Scribe code from UVA, but the new MediaWiki version broke some of the Scribe features.  This is our current configuration:

MediaWiki 	1.27.1
PHP 	7.0.21 (cgi-fcgi)
MySQL 	5.6.34-log
Omeka 	2.4.1

We would like to upgrade to these versions:
MediaWiki 1.29.0 
Omeka 2.5 

Are there any plans to update the UVA Scribe code?

Thank you

**Comment by jasonroma** [comment]
Hello,
We do not have a plan in place to update our currently available version.
