### ISSUE TITLE
export plugin fails after 5230 files with no error message

### ISSUE THREAD

**Issue by rileyjrs** [LibraryofVA/MakingHistory-transcribe-2.0#6]
Hi -

www.nsmlv.org/omeka has 2 collections.  Collection #2 Citation index to the Las Vegas Review-Journal, 1930 - 1951 has 90 items.  There are about 500 files in each item (about 18 items have been approved).  We want to export all the approved items so we can remove them from our web site for performance reasons.  We used the export plugin, which exports by collection, in an attempt to export the entire Collection #2.  The plugin writes 5228 items to the omeka/plugins/Export/TXT directory, then fails.  We can't find an error message.  Is there a log to check?  Or do you know why the export fails?  Or is there a different way to export the data?

Thank you in advance

**Comment by jasonroma** [comment]
The only log by default is /application/logs/errors.log but the plugin errors might now show in there depending on what is going on. The first thing I would test for is if it was timing out during building the TXT files or zipping them up. Try creating a new private collection, move 1 or 2 approved items to that collection, and attempt exporting. Knowing that the plugin works is good to know before we start looking at why it doesn't work with a given collection or sample size.

**Comment by rileyjrs** [comment]
Hi -

We created a new private collection and moved one item into it (the order of all the files changed, which is truly annoying since we spent a lot of time ordering them in the original collection).  We then tried a txt export.  Most, but not all the txt files were created, and no zipping was done.  No errors were logged in /application/logs/errors.log.

**Comment by jasonroma** [comment]
Sorry about the order of the items changing. /themes/scribe/collections/show.php, line #20-26 contains the loop of items being gathered before printing to screen. You can change the sort_field there but it will change it for all collections. You could warp an if/else around it looking for a specific collection id and then change the sort_field to whatever would be helpful for that one collection. 

`if (collection('id')==27 {
            $collection_items = get_records('Item',
            array(
                'collection' => $collection['id'],
                'sort_field' => 'Scripto,Weight',
                'sort_dir' => 'a',
            ),
            999);
} else {
}`

**Comment by jasonroma** [comment]
Which export option are you using, whats the url? And do your files match the ones found at https://github.com/LibraryofVA/plugin-Export-2.0/tree/master/views/admin/index or are there enhancements/changes to them?

**Comment by rileyjrs** [comment]
Thank you for the information about changing the order of items.  I am not a programmer, but will take a look and see if I can make some changes that work.  With regard to the export option, the url is https://www.nsmlv.org/omeka/admin/export/index/text?c=4.  We made some very minor changes to the footer.php files and the header.php files to change the appearance of web pages.  We also edited the footer.php file so it works with php version 7.  Specifically, we  changed mysql_ function calls to mysqli_ and changed some of the parameters that are passed to the functions.

**Comment by jasonroma** [comment]
I've added some error logging to https://github.com/LibraryofVA/plugin-Export-2.0/blob/master/views/admin/index/text.php to hopefully help us determine what is going on. If you update the corresponding file on your server it will create a export.log file in your omeka/plugins/Export/TXT directory during export. Attach the resulting file to your next comment and I'll see if I can help.

**Comment by rileyjrs** [comment]
[export.txt](https://github.com/LibraryofVA/MakingHistory-transcribe-2.0/files/1312942/export.txt)
Hi -
export.log was renamed to export.txt so it would upload to this site.  All the files (145) got copied, but no zip.
Thank you for your help

**Comment by jasonroma** [comment]
Thank you, that helped me see how far through the code it made it. After some googling I found that PHP 7.x sometimes comes without the ZipArchive library, which is right around where the script failed. Your going to want to install or verify that php7.0-zip is already installed.

**Comment by rileyjrs** [comment]
Hi -
When I try to check for loaded php extensions, it looks like the zip is there:
$ php -r "print_r(get_loaded_extensions());"
Array
(
  ...
    [46] => zip
   ...
)

**Comment by jasonroma** [comment]
It looks like it. You can try the below to make sure the ZipArchive class is available but I don't have a reason to believe it wouldn't be. Adding more logging to the ../text.php file now.
`php -r "print_r(class_exists(ZipArchive));"`

**Comment by rileyjrs** [comment]
Hi -

Nothing is returned with this command:
php -r "print_r(class_exists(ZipArchive));"
so I am not sure if the php zip extension is working or not.  Our site is hosted by Dreamhost, and I don't have a lot of privileges which hampers testing.  I contacted Dreamhost to ask them to check if it's installed and working.  Thank you for your help.

**Comment by jasonroma** [comment]
php -r "print_r(class_exists(ZipArchive));" should have returned 1 or True if the class was available. Please let me know what Dreamhost comes back with.

**Comment by rileyjrs** [comment]
Hi -  Dreamhost says the ziparchive extension is installed.  I created a file named test.php which contains the following:

<?php
$zip = new ZipArchive;
$res = $zip->open('test.zip', ZipArchive::CREATE);
if ($res === TRUE) {
    $zip->addFromString('test.txt', 'file content goes here');
    $zip->close();
    echo 'ok';
} else {
    echo 'failed';
}
?>

then I executed it and it returned "ok" and created a zip file:

$ php test.php
ok

-rw-rw-r-- 1 lan_t3rn pg8740520      138 Sep 21 21:30 test.zip

Do you think some more error logging is needed for the Scripto plugin or am I doing something wrong?

**Comment by jasonroma** [comment]
I've added more error logging to hopefully pinpoint where it is failing. Please rename the attached to text.php and replace the file in your plugins/Export/views/admin/index/ directory. Please let me know what the new log file shows after running an export. 
[text.txt](https://github.com/LibraryofVA/MakingHistory-transcribe-2.0/files/1327002/text.txt)

**Comment by rileyjrs** [comment]
[export.log](https://github.com/LibraryofVA/MakingHistory-transcribe-2.0/files/1327832/export.log)
Hi -
Here is the log file.  Thank you very much for your help.

**Comment by jasonroma** [comment]
Thanks for the log. Something is up with the ZipArchive line itself. When they proved you have the class they called it slightly different. I didn't think much of it but your most recent logs shows the script failing at line 122 and 123 which is:
`$zip = new ZipArchive();
$zip->open($destination,$overwrite ? ZIPARCHIVE::OVERWRITE : ZIPARCHIVE::CREATE)`

1) Your first line of code from Dreamhost was `open('test.zip', ZipArchive::CREATE); `
Is there anything before that? Like a `$zip->` or `$zip = new ZipArchive();`?

2) I'm attaching a new text.php file that ultimately will not create a zip but instead tests new/different ways of calling $zip->open to see if any of them work. But if your server is working without call new ZipArchive or $zip->open it will be very difficult to help as I have never seen it called that way and cannot get my server to mimic that behavior. 

Please answer the question 1) or send a copy of your test.php provided by Dreamhost. 

2) Please rename the attached [text.txt](https://github.com/LibraryofVA/MakingHistory-transcribe-2.0/files/1327987/text.txt) to text.php and replace the file in your plugins/Export/views/admin/index/ directory. Please let me know what the new log file shows after running an export.

**Comment by rileyjrs** [comment]
Hi -
Oops, sorry I forgot about the test.php question, here is the whole file - NOTE - the zip file must already exist for this script to work:

[bombur]$ cat test.php

<?php
$zip = new ZipArchive;
if ($zip->open('test.zip') === TRUE) {
    $zip->addFile('/home/lan_t3rn/logs/test.txt', 'newname.txt');
    $zip->close();
    echo 'ok';
} else {
    echo 'failed';
}
?>

The most recent copy of the text.php produced this log:

[bombur]$ cat export.log
2017-09-25 09:26:21am

LVRJ Drawer 01, Part 01
End of text file creation reached
Zip file destiniation does not exist
144 valid/exisiting files to zip.
new ZipArchive worked
#1 worked
#2 worked
#3 worked

The txt files were created, but still no zip file (the destination is missing per the log file above?):

[bombur]$ ls -ltr
total 1068
-rw-r--r-- 1 lan_t3rn pg8740520     63 Sep 25 09:26 d_1_c_000002_transcription.txt
-rw-r--r-- 1 lan_t3rn pg8740520    107 Sep 25 09:26 d_1_c_000004_transcription.txt
...
-rw-r--r-- 1 lan_t3rn pg8740520     60 Sep 25 09:26 d_1_c_000485_transcription.txt
-rw-r--r-- 1 lan_t3rn pg8740520     71 Sep 25 09:26 d_1_c_000236_transcription.txt
-rw-r--r-- 1 lan_t3rn pg8740520     66 Sep 25 09:26 d_1_c_000235_transcription.txt
-rw-r--r-- 1 lan_t3rn pg8740520     61 Sep 25 09:26 d_1_c_000242_transcription.txt
-rw-r--r-- 1 lan_t3rn pg8740520    214 Sep 25 09:26 export.log

**Comment by jasonroma** [comment]
I think we made progress. 
"Zip file destination does not exist" -> that is the resulting message when Zip file does not exist. A bit cryptic and I will be clarifying it but not a problem.

That last version of text.php did not attempt to create a zip, I was just testing commands to see which if any worked. It appears all the new commands worked so I will put the most complete command in the newest version of [text.txt](https://github.com/LibraryofVA/MakingHistory-transcribe-2.0/files/1330215/text.txt) attached to this response and hopefully it will work once on your server.

If it doesn't work it appears we have one more option. The test.php you pasted the contents of works on your server once a Zip file already exists. If the attached script doesn't work we can alter it, you create a Zip file in the TXT directory, and we cross our fingers.
